# Generated by Django 6.0 on 2026-01-05 12:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('default_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='ON', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_distance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum allowed distance in meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Electricity Meter',
                'verbose_name_plural': 'Electricity Meters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('distance_from_default', models.DecimalField(decimal_places=2, help_text='Distance from default location in meters', max_digits=10)),
                ('is_within_threshold', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='gps.electricitymeter')),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter', '-timestamp'], name='gps_locatio_meter_i_93cd41_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeterStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('reason', models.CharField(choices=[('LOCATION_CHANGE', 'Location Change'), ('MANUAL', 'Manual Control'), ('SYSTEM', 'System Action'), ('METER_REPORTED', 'Meter Reported')], default='SYSTEM', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='gps.electricitymeter')),
            ],
            options={
                'verbose_name': 'Meter Status Log',
                'verbose_name_plural': 'Meter Status Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter', '-timestamp'], name='gps_meterst_meter_i_466c57_idx')],
            },
        ),
    ]
