# Generated by Django 6.0 on 2026-01-11 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='available_units',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Available units for the meter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='connection_status',
            field=models.CharField(default='OFFLINE', help_text='Connection status (ONLINE/OFFLINE)', max_length=20),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Current balance of the meter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time the meter was seen/connected', null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='relay_status',
            field=models.CharField(default='OFF', help_text='Relay status (ON/OFF)', max_length=10),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='tamper',
            field=models.BooleanField(default=False, help_text='Tamper detection status'),
        ),
    ]
