# Generated by Django 6.0 on 2026-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_electricitymeter_available_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current RMS current', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total energy consumed in kWh', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Active power in kW', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current RMS voltage', max_digits=10, null=True),
        ),
    ]
